#! /bin/bash

printf "\nFetching upstream...";
git fetch upstream master;
sleep 1;

printf "\nPulling updates from upstream...";
git pull upstream master;
sleep 1;

printf "\nPushing updates to origin.";
git push origin master;
sleep 1;