#! /bin/bash

# kill current Django process
PORT_NUMBER=8000
lsof -i tcp:${PORT_NUMBER} | awk 'NR!=1 {print $2}' | xargs kill

# transpile all ES6+ to ES5
rm -rf node_modules/*
npm install
npm run transpile

# compress static files into /staticfiles/
python manage.py collectstatic --noinput -i *.es6 -i *.scss
echo "Static files collected."

if [[ "$*" == kill ]]
then
    echo "Process at port 8000 killed."
else
    nohup ./manage.py runserver 2>&1 >/dev/null &
    echo "View update at http://127.0.0.1:8000/"
fi